#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# set background
if [ -x "$(command -v feh)" ]; then
  feh --no-fehbg --bg-scale "$SCRIPTPATH/assets/down.jpg"
fi

leftwm-command "UnloadTheme"

pkill picom
pkill polybar
pkill dunst
