#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


# down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


# boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --config "$SCRIPTPATH/config/picom/picom.conf" &> /dev/null &
fi

if [ -x "$(command -v dunst)" ]; then
    dunst -config "$SCRIPTPATH/config/dunst/dunstrc" &> /dev/null &
fi


# set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"


# set background
if [ -x "$(command -v feh)" ]; then
  feh --no-fehbg \
      --bg-scale "$SCRIPTPATH/wallpapers/alveolar.png" \
      --bg-scale "$SCRIPTPATH/wallpapers/alveolar.png"
fi

index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="mainbar$index"
  monitor=$monitor offset=$x width=$width polybar -c "$SCRIPTPATH/config/polybar/polybar.config" $barname &> /dev/null &
  let index=indextemp
done

